### ISSUE TITLE
Check 5.14 should not check for container MaximumRetryCount

### ISSUE THREAD

**Issue by jscheytt** [diogomonica/docker-benchmark#542]
We have a few Docker services where we set the max_attempts like prescribed:

```yaml
    deploy:
      restart_policy:
        max_attempts: 5
```

Still, Check 5.14 fails in Docker Swarm. And I think this check fails for the wrong reasons:

This line https://github.com/docker/docker-bench-security/blob/4edccd78595d1f0d6d71b0ae5316e0c70c537f38/tests/5_container_runtime.sh#L612 checks not only services but also containers. On a container, the MaximumRetryCount will only be set if the restart_policy is set to "on-failure": https://github.com/moby/moby/issues/10809 If your restart_policy is of any other type, this field will be set to zero. So this will give false negative findings even when you set the max_attempts but use a different restart_policy condition (in Docker Swarm it's "any").

Btw I even tried setting the `deploy.restart_policy.condition` to any other type and in Docker Swarm I still got containers with MaximumRetryCount of 0.

Try this simple example to reproduce:

```sh
cat <<EOF > postgres.yaml
version: "3.9"
services:
  postgres:
    image: postgres:14.9
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    deploy:
      restart_policy:
        max_attempts: 5
EOF
docker stack up --prune -c postgres.yaml postgres
# Check max_attempts in Docker service (will be 5):
docker inspect --format MaxAttempts='{{ .Spec.TaskTemplate.RestartPolicy.MaxAttempts }}' $(docker service ls -q -f name=postgres)
# Check maximum retry count in container (will be 0):
docker inspect --format MaximumRetryCount='{{ .HostConfig.RestartPolicy.MaximumRetryCount }}' $(docker ps -q -f name=postgres)
```

I would like to propose to only check Docker services and not containers in 5.14.

**Comment by konstruktoid** [comment]
Hi @jscheytt and thanks for creating the issue, but as stated on https://github.com/docker/docker-bench-security/blob/master/tests/5_container_runtime.sh#L589: "Ensure that the 'on-failure' container restart policy is set to '5' (Automated)", and in the CIS Docker Benchmark:
"By using the `--restart` flag in the `docker run` command you can specify a restart policy for how a container should or should not be restarted on exit. You should choose the `on-failure restart` policy and limit the restart attempts to `5`."

**Comment by jscheytt** [comment]
Thanks for the clarification, I missed that point!

However, as I stated above, even when I set the condition to "on-failure", the resulting container still has a MaximumRetryCount of zero.

**Comment by konstruktoid** [comment]
What does `docker-bench-security.sh -c check_5_14` return?

**Comment by jscheytt** [comment]
Actually, I cannot really reproduce this locally (MacBook w/ docker v24). The specific circumstances under which this is happening is RHEL 8.9 with docker v23.0.1, and out of about 40 services (all exactly equally configured for 5.14, now also with "condition: on-failure"), the benchmark script only marks two services as not meeting the criteria (Artifactory and a Postgres). And on some environments, even **all** services are marked as non-passing. I hoped I could find some way to more easily analyse what is going wrong here, but I guess trying to reproduce the exact same circumstances will be a bit cumbersome, so for now I will just deactivate 5.14 ...
